### ISSUE TITLE
Missing Information in the json file 

### ISSUE THREAD

**Issue by CKY-** [makehumancommunity/makehuman-plugin-for-blender#13]
Can you please update the assets.json to supply the files for models, materials, and rigs can you also add a  new value for materials that is belongsto and all other assets need there aomapTexture file supplied.. 

Please update this?

**Comment by joepal1976** [comment]
I have now made several changes to the JSON file:

* All existing content types should now have files listed
* Materials has a "belongs_to" field supplied
* All nodes have new keys "created" and "changed" with ISO dates for when the node was created and last changed respectively

As an example, a material entry now looks like this:

    "178": {
        "username": "Joel Palmius", 
        "files": {
            "mhmat": "http://www.makehumancommunity.org/sites/default/files/materials/1/2089531841/TransparentLabGlasses.mhmat", 
            "thumb": "http://www.makehumancommunity.org/sites/default/files/materials/1/10995721/TransparentLabGlasses.thumb", 
            "render": "http://www.makehumancommunity.org/sites/default/files/clothes/1/43884045/TransparentLabGlassesScreenshot.png", 
            "diffuse": "http://www.makehumancommunity.org/sites/default/files/materials/1/1371019831/TransparentLabGlassesDiffuse.png"
        }, 
        "changed": "2015-12-19", 
        "uid": 1, 
        "license": "CC0", 
        "title": "Transparent lab glasses", 
        "created": "2015-12-19", 
        "nid": 178, 
        "belongs_to": {
            "belongs_to_type": "clothes", 
            "belongs_to_title": "Crude lab glasses", 
            "belonging_is_assigned": true, 
            "belongs_to_id": 158
        }, 
        "type": "material", 
        "description": "More fancy texture for Crude Lab Glasses. Glass part is actually transparent. "
    },

This for a material where the belonging was assigned. For a material where the belonging isn't assigned, it will look like this:

    "196": {
        "username": "grinsegold", 
        "files": {
            "mhmat": "http://www.makehumancommunity.org/sites/default/files/materials/1168/1529470351/Ignore me.mhmat", 
            "diffuse": "http://www.makehumancommunity.org/sites/default/files/materials/1168/1296754301/MH Makeup smokey eyes.png", 
            "render": "http://www.makehumancommunity.org/sites/default/files/clothes/1168/1612232305/Smokey eyes demo.png"
        }, 
        "changed": "2015-12-29", 
        "uid": 1168, 
        "license": "CC0", 
        "title": "Make-up layer \"Smokey eyes\"", 
        "created": "2015-12-29", 
        "nid": 196, 
        "belongs_to": {
            "belonging_is_assigned": false
        }, 
        "type": "material", 
        "description": "2k alpha texture for overlaying as shown in the picture. Ignore the mhmat-file."
    },

Leaving the issue open for now, since it a) needs testing and b) I haven't addressed the aoMap issue.

**Comment by joepal1976** [comment]
This is no longer relevant, and the asset downloader plugin has moved to a separate repo.
