### ISSUE TITLE
Getting ready to close code on Kinect v2 version

### ISSUE THREAD

**Issue by Palmer-JC** [makehumancommunity/makehuman-plugin-for-blender#28]
The small (x64 & x86) wrapper DLL's have their own [repo](https://github.com/Palmer-JC/KinectToJSON), which might be final.  They are in a separate repo, since this is c++, but the final DLLs will be in the zip file here, so all you would need to do is install the plugin & the [kinect runtime](https://www.microsoft.com/en-us/download/details.aspx?id=44559).

The documentation in this repo is underway.  Code is very close.  I was wondering about deleting the code in the cli & makehuman directories?  Newer versions are in other repos, but thought others should do the deletions not I.

If they were deleted, I would move up lower readme.md to top level, and mostly say use the community edition of MH or add plugins [referencing ](http://www.makehumancommunity.org/content/plugins.html).

Also, where is the community edition of MH?

**Comment by joepal1976** [comment]
I've now moved away the stale stuff. Feel free to rearrange the repo as you see fit.

**Comment by joepal1976** [comment]
Also, with these changes, the repo name no longer makes much sense. If it doesn't cause too much inconvenience, maybe we should also consider renaming the repository to something that says what it is.

**Comment by Palmer-JC** [comment]
Ok, I got everything up there.  You can rename.  I am still testing / documenting.  

Already see one problem in that the Blender version is set to 2.80.  I did that to take screen shots, so they would not quickly look old.  It does not run there.  Am planning to get repo final for 2.79, then copy the zip file to 'Pre-blender-2-80.zip' just before working on port in earnest.

FYI, when using the Kinect skeleton in IK configuration, you have to select both hip bones & lower spine when bending at knees.

**Comment by joepal1976** [comment]
I haven't really got acces to a kinect, so won't be testing any time soon. :-)

First problem with renaming is what to call it. I'll sleep on it and see to doing something about it tomorrow.

**Comment by joepal1976** [comment]
I landed in "makehuman-plugin-for-blender". The repo is now renamed, so closing this issue.
