### ISSUE TITLE
Importer crashes in blender that is shipped with ubuntu 18.04

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman-plugin-for-blender#36]
Everything works fine on ubuntu 18.04 when using a manually downloaded blender. However, when using the blender that is shipped by ubuntu (ie a customized version that uses the system python), there is a crash with an infinite loop for when the importer tries to recalculate normals of an imported mesh. 

The output is a bunch of C memory locations that makes little sense, will have to debug further to understand what's happening.

**Comment by Palmer-JC** [comment]
Also, please goto to the Kinect tab while there.  I do not expect it to work, but fail gracefully, by graying out the Record button.  It should also write to console saying 'Kinect only works on a Windows operating system.', but not actually generate an exception.

I do not have a Linux system.

**Comment by joepal1976** [comment]
Will close this as "won't fix", as we're going to strongly recommed against using Ubuntu's version of Blender. 

The kinect tab works as expected in linux (ie gracefully does nothing) when using a blender version from blender's homepage. This has been tested in both blender 2.79 and 2.80.
