### ISSUE TITLE
facial bones not following

### ISSUE THREAD

**Issue by j2l** [makehumancommunity/makehuman-plugin-for-blender#37]
Tried 1.2 alpha with blender 2.9b on Win10 with default rig presets.
(your update decided me to buy kinect and adapter. Can't wait to test it!)
When I sync MH in bones/IK after changing pose in makehuman app, I get facial bones not following the face:
![image](https://user-images.githubusercontent.com/65325/48983968-09b0c180-f0f6-11e8-96aa-f4ab842446ce.png)
Rest of the body is ok.

**Comment by joepal1976** [comment]
Thanks for testing. That's very helpful. 

For this particular issue, it is known and previously reported in https://github.com/makehumancommunity/makehuman-plugin-for-blender/issues/33

I'm going to close this issue and we can continue the conversation there.
