### ISSUE TITLE
Clean up code structure, testing needed

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman-plugin-for-blender#38]
I've begun tidying up the code structure a bit. In this I've mainly broken up some of the large python files into smaller one-class-per file chunks, and placed these in subdirectories. 

The current status is in the branch https://github.com/makehumancommunity/makehuman-plugin-for-blender/tree/_feature_refactor_code_structure

To my knowledge, the functionality should be unaffected, but I haven't been able to test the kinect stuff. 

If this could receive some cursory testing, I'll merge the refactoring to the main branch.

**Comment by Palmer-JC** [comment]
Good, I have changes I did about a month ago, mainly 2 bugs & the direct to shapekeys of expressions.  Needed to modify the main __init__.py to do so.

Been working on redesigning a Blender exporter to recursively analyze Cycles node trees for the last month, since the internal renderer is going away.  It has been published for testing.  Could not really compartmentalize to work on both at the same time. Still only runs on 2.79, but my productivity on it has really dropped. Time to switching back to here, now.

**Comment by Palmer-JC** [comment]
Ok, well I am going to drop the Fork repo, where I update to that, PR, & approve my own PR.

Having a direct clone in a new local repo, the kinect operations themselves worked.  It is missing the list of the bodies captured for assignment.  This list can hold up to 6 entries, one for each body that got captured during the last session.

I'll figure out / fix this, transfer bugs & expression direct to shape keys on this branch, maybe today.  I still am trying to figure out some issues.  Also, that '1 Right' is for diagnostics.  Will comment it out for the commit, but leave so I can turn it on locally.
![kinect with list](https://user-images.githubusercontent.com/7916131/50299506-bcebac80-044f-11e9-9685-7399904a3cc7.JPG)

**Comment by Palmer-JC** [comment]
Your commit kind caused a bunch of problems.  I made a bunch of changes including that one.  Did not think you did anything & committed.

I pushed, or tried & was rudely awakened.  Using Netbeans started getting questions.  I hit buttons like 'rebasing' or something.  Thought I just screwed up my local, so I just cloned again, switched to branch, copied my changed files & tested.

Trying to commit locally, I get message I have no clue what is.  Did this change gitHub?
![detached head](https://user-images.githubusercontent.com/7916131/50313892-e3730d00-047a-11e9-9b22-33c1367da662.JPG)

**Comment by joepal1976** [comment]
As far as I can see, nothing has reached github so far. I don't find any changes in either of the branches master, _feature_blender_28 or _feature_refactor_code_structure. 

Can you reset your local repo ("git reset [commit hash]") back to the status before you started trying to merge the changes? If so, then maybe you can make a diff against master and get a list with all the changes, independent of my changes in the refactor branch.

I think you did something strange with the rebase, causing the git state to hang loosely in the air. I'd be careful with trying to base further work on that git state. You can read more about detached heads here: https://www.git-tower.com/learn/git/faq/detached-head-when-checkout-commit

**Comment by Palmer-JC** [comment]
Ok, I got it straightened out.  I committed everything, but a new zip file.  I also broke out into a ui file for each of the other 2 tabs.  There were a couple of other linkage issues fixed as well.

The multiple destinations (pose lib or shapekey) is also in this commit.  Please let me know when this has been merged into master.

**Comment by joepal1976** [comment]
Ok, nice. I'll take a look at this and a few last things with blender 2.80 once my family has left after christmas. So a merge to master is likely to take a few days.

**Comment by joepal1976** [comment]
I have now tested a bit and the merged everything to master. I also merged the blender 2.80 code to master and tested your changes with that too.

Everything seemed to work in principle, but there were a few observations. 

First, under blender 2.80 I get a warning:

```
Warning: class AnimationProps contains a properties which should be an annotation!
/home/joepal/.config/blender/2.80/scripts/addons/MH_Community/kinect_sensor/kinect_ui.py:19
    make annotation: AnimationProps.id
    make annotation: AnimationProps.name
```

This is probably not a big deal, but I didn't want to mess around with the kinect code since I can't test it.

Regarding the shape key import of expressions, it seemed to create the appropriate shape keys. However, they seemed to be both applied once and then available to be applied a second time. 

For all the following the expression is set to "None" in MakeHuman.

This is before import, ie rest state:

![shapekeys_before](https://user-images.githubusercontent.com/10105480/50477233-b919d600-09cb-11e9-9add-8285edaafc6a.png)

This is after clicking the "transfer" button, having specified the "Anger" tag. All shapekeys are at 0.0, but the toon is still making a face:

![shapekeys_rest](https://user-images.githubusercontent.com/10105480/50477239-bcad5d00-09cb-11e9-8a7f-04ab90ef53c5.png)

This is with the "Anger01" expression applied, seemingly twice:

![shapekeys_anger](https://user-images.githubusercontent.com/10105480/50477228-b3bc8b80-09cb-11e9-9ff8-d2a6c753f2f4.png)

Maybe the shape keys weren't set to 1.0 before modifying vertex positions?

**Comment by Palmer-JC** [comment]
I think this is because the last expression is still reflected in the facial bones.  I thought about resetting back to the rest pose, but that would not actually work if you also allowed location changes to get the really good expressions.  Do not know why.

What does get everything back, is going to MH setting expression back to none, (it might already be but expression is out of sync with UI), do a sync pose.  You probably cannot do another expression transfer, since I do not think 'None' is an actual named expression.  Will think about another way to do a proper clean up.

**Comment by joepal1976** [comment]
I think this issue is outdated.

**Comment by j2l** [comment]
> Regarding the shape key import of expressions, it seemed to create the appropriate shape keys.
@joepal1976, I can't make it work in Blender 2.81 and 1.2a4, plugin 0.6.2. 
It does reset bones to rest pose but no shape key is created or updated.
My process is:
keep all settings
in MH: None pose
Import human
in MH: Cry01 pose
select armature, sync with MH
select body shift select armature, tag=Cry01, click Transfer
=> pose is reset to rest, while being set in Pose position, mode is now Pose (not Ojbect Mode)
no shape key created

Could you please explain your process?
@Palmer-JC, or is it another process now?

Thank you for your help!
Happy holidays!

**Comment by Palmer-JC** [comment]
Putting a comment in an old issue, not really the best idea.  On the forum, I did describe some stuff to be aware of [Here](http://www.makehumancommunity.org/forum/viewtopic.php?f=3&t=18170#p49614).

The most note-able is making sure your remove the modifiers which change vertices.  Also, you can bring up an info window to see the effects of the operation.
