### ISSUE TITLE
Extra mesh created with zero vertices

### ISSUE THREAD

**Issue by Palmer-JC** [makehumancommunity/makehuman-plugin-for-blender#40]
I have not looked at the code, but I am using an MH to test out my 2.80 exporter.  I found that I got an extra mesh also made.  Not sure what this is.  The name is Body.  Maybe it only occurs when there a  parented skeleton.  See last mesh, Mr_MHBody
![extra_mesh](https://user-images.githubusercontent.com/7916131/50565936-0666b200-0d02-11e9-800f-d73737f027ef.jpg)

**Comment by joepal1976** [comment]
This is working as expected.
