### ISSUE TITLE
No Rig while imoprt

### ISSUE THREAD

**Issue by Eloque** [makehumancommunity/makehuman-plugin-for-blender#43]
When importing into Blender 2.8 with the sync function, no rig can be found. The rig is present when importing via file into Blender 2.79. 

This is the model when imported in Blender 2.79 and then opened in Blender 2.8;
![image](https://user-images.githubusercontent.com/4184679/52061079-d9f6bd80-256d-11e9-8a58-09027a92f1eb.png)

This when imported directly in Blender 2.8
![image](https://user-images.githubusercontent.com/4184679/52061112-e549e900-256d-11e9-9db7-1a0579c69b3f.png)

It was suggested that it might have been a layer thing, and there is indeed a difference. This is via 2.79 to 2.8;
![image](https://user-images.githubusercontent.com/4184679/52061155-fc88d680-256d-11e9-893d-1a80329ca667.png)

This is directly imported in 2.8
![image](https://user-images.githubusercontent.com/4184679/52061180-0f031000-256e-11e9-9a02-13a1680aadf6.png)

Also, when based on the import I try to generate the rig, this error pops up;
![image](https://user-images.githubusercontent.com/4184679/52061228-28a45780-256e-11e9-9840-b7b70534b810.png)

**Comment by Aranuvir** [comment]
I do not understand the problem, since both images show a rig, though they are different. The first one is probably a MHX rig. There was neither further input for more than a year, nor any similar bug reports. Closing...
