### ISSUE TITLE
Plugin fails to install on some computers

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman-plugin-for-blender#44]
As per youtube comments, it would seem the plugin fails to install on some computers. 

Having tested this with the following setup:

* Ubuntu 18.04
* Blender 64-bit, commit ec471a9b1c14, dated 2019-02-16
* MH plugin from github master

... I fail to reproduce the issue. 

If you still have problems with installation on the latest blender, please provide the following information:

* What operating system are you using? 
* Exactly which version of blender are you using, at least date and commit hash
* Exactly which version of the MH plugin are you using? Did you download from github, or did it come from alpha 2 for example?

**Comment by DShiznit** [comment]
I'm getting a syntax error when I try to enable the plugin (I downloaded it twice from github) in Blender 2.79 on Windows 7 64-bit. I tried reinstalling blender to no avail. The version that came bundled with MakeHuman 1,1,1 activates fine.

**Comment by joepal1976** [comment]
As Blender 2.8x is now released as stable, we are no longer prioritizing 2.79 backwards compatibility. New development is done for, and tested against, blender 2.80 and MakeHuman 1.2.0.

Without having seen your error message (which should contain more information, such as where in the code it occurred), my guess is you've run into a compatibility issue with 2.79.

**Comment by mhotep** [comment]
Having the same issue. I downloaded the plugin from github. Went through a lot of work to follow a tutorial only to get the error.

System Information
Operating system: Windows 10
Graphics card: AMD Radeon HD 7420G

Blender Version
Broken:
(example: 2.79b release)
(example: 2.80, edbf15d3c044, blender2.8, 2018-11-28, as found on the splash screen)
Worked: (optional) 2.79 2017-09-11

Short description of error
Loading MH community plug-in v 0.5
Loading kinect Sensor plug-in
Traceback (most recent call last):

File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
  mod = __import__(module_name)
File "C:\Users\Nnamdi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\__init__.py", line 23, in <module>
  from . import kinect_sensor # directory
File "C:\Users\Nnamdi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\kinect_sensor\__init__.py", line 20, in <module>
  from . import kinect_ui
File "C:\Users\Nnamdi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\MH_Community\kinect_sensor\kinect_ui.py", line 13
  id: IntProperty()
    ^

SyntaxError: invalid syntax

Exact steps for others to reproduce the error
The error happens after installing the plugin and attempting to enable it.
Based on the default startup or an attached .blend file (as simple as possible).

![mh community plugin error Annotation 2020-07-26 164012](https://user-images.githubusercontent.com/6558689/88488943-f014ec80-cf5e-11ea-9d81-9657f7cb7c39.jpg)

**Comment by joepal1976** [comment]
The current version of the community plugin is 0.6.3, and it is tested against blender 2.83. Have you tried this combination?

The latest version of the community plugin can be downloaded here: http://download.tuxfamily.org/makehuman/plugins/
