### ISSUE TITLE
IsADirectoryError: [Errno 21]

### ISSUE THREAD

**Issue by TcaManager** [makehumancommunity/makehuman-plugin-for-blender#47]
Hi, I've got this weird error when I try to add the plugin from the zip file in Blender 2.80 manual build in Ubuntu 19.04. It looks like the plugin is installed and activated but something went wrong and I get no import menu for mhx2 even when restarting Blender. 
I don't get why it sees pyfile, path_dest as directories? /home/julien is my home dir but all software are installed somewhere else.
Help appreciated. Thanks.

> Traceback (most recent call last):
> File "/home/julien/build_linux/bin/2.80/scripts/startup/bl_operators/userpref.py", line 646, in execute
>     shutil.copyfile(pyfile, path_dest)
>   File "/home/julien/build_linux/bin/2.80/python/lib/python3.7/shutil.py", line 120, in copyfile
>     with open(src, 'rb') as fsrc:
> IsADirectoryError: [Errno 21] Is a directory: '/home/julien/'
> addon_utils.disable: MH_Community not disabled
> Modules Installed (MH_Community) from '/home/julien/makehuman-plugin-for-blender/blender_distribution/MH_Community_for_blender_280.zip' into '/home/julien/.config/blender/2.80/scripts/addons'
> Loading MH community plug-in v 0.4
> Loading sync plug-in
> sync plug-in loaded
> Loading kinect Sensor plug-in
> kinect Sensor plug-in loaded
> MH community plug-in load complete
> Warning: class AnimationProps contains a properties which should be an annotation!
> /home/julien/.config/blender/2.80/scripts/addons/MH_Community/kinect_sensor/kinect_ui.py:19
>     make annotation: AnimationProps.id
>     make annotation: AnimationProps.name
> Writing userprefs: '/home/julien/.config/blender/2.80/config/userpref.blend' ok
> Saved session recovery to '/tmp/quit.blend'
>

**Comment by TcaManager** [comment]
Looks like I got rid of the warning, easily...
Now I get this everytime I start Blender

> found bundled python: /home/julien/build_linux/bin/2.80/python
> Loading MH community plug-in v 0.4
> Loading sync plug-in
> sync plug-in loaded
> Loading kinect Sensor plug-in
> kinect Sensor plug-in loaded
> MH community plug-in load complete

Which sounds nice (though I don't have any kinnect stuff... But I still can't get any import menu for mhx2 though the plugin appears activated.
I got another weird problem now, when I de-activate and re-activate the plugin, without restarting Blender, I get
> Exception in module register(): /home/julien/.config/blender/2.80/scripts/addons/MH_Community/__init__.py
> Traceback (most recent call last):
>  File "/home/julien/build_linux/bin/2.80/scripts/modules/addon_utils.py", line 384, in enable
    mod.register()
>  File "/home/julien/.config/blender/2.80/scripts/addons/MH_Community/__init__.py", line 99, in register
    registerKinectConstantsAndSettings()
>  File "/home/julien/.config/blender/2.80/scripts/addons/MH_Community/kinect_sensor/kinect_ui.py", line 18, in registerKinectConstantsAndSettings
>    bpy.utils.register_class(MHC_UL_AnimationItems)
> ValueError: register_class(...): already registered as a subclass

But when I restart Blender and re-activate, no error, nor warning, but still no Import menu for mhx2. Did I misunderstood? Should there be an import menu? Maybe I'm looking at the wrong panel.

**Comment by joepal1976** [comment]
MHX2 and "makehuman plugin for blender" are two different things. MHX2 is an export/import format. "makehuman plugin for blender" is an bunch of features such as:

- online/socket integration with makehuman
- rig support
- kinect support.

You can find MHX2 here: https://bitbucket.org/Diffeomorphic/mhx2-makehuman-exchange/src/default/

This said: I think MHX2 isn't finished in its porting to 2.80. One thing missing is the import menu entry. However, you should be able to find MHX2 on the "N" panel (or possibly the "T" panel, I keep mixing these up). There you should be able to find an "import" button which does the same as the menu entry.

**Comment by Aranuvir** [comment]
Just to make sure, even if the OP is talking about mhx2 he seems to be reporting an issue with the community plug-in.
>Loading MH community plug-in v 0.4
I can confirm the problem, though I'm not sure whether this a bug in the plug-in or in Blender. Recently I purchased some plug-ins from BlenderMarket and was strongly discouraged to use the built-in install tool...
