### ISSUE TITLE
Better defaults for MakeClothes

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman-plugin-for-blender#61]
Currently feed shouldn't be on ground and I'd suggest to unmask helpers. Further add simple materials to helpers.

**Comment by Aranuvir** [comment]
This is partially fixed, now. Masking helpers is discussible.

**Comment by joepal1976** [comment]
Since it's easy and helpful to toggle the mask back and forth depending on what part of the body you're modeling for, I think mask should be default. 

Anyway, the fixes work for me so marking as fixed.
