### ISSUE TITLE
Multiple materials on body after import to Blender

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman-plugin-for-blender#64]
Importing a mesh with default material settings to Blender creates 8 material slots for the body mesh.

**Comment by joepal1976** [comment]
My bad. I must've committed a half-way finished experiment. The idea is to provide an option for setting up material copies for parts of the body, ie one slot for lips, one for fingernails and so on. But it should be an option and not enabled per default.

I'm on it, but I won't be able to fix it tonight.
