### ISSUE TITLE
BUG? Error when importing to Blender 2.82

### ISSUE THREAD

**Issue by LadyRover** [makehumancommunity/makehuman-plugin-for-blender#65]
Hi,

when I want to import into Blender 2.82 I get the attached error.
Is there anything I can do to fix this?

Kind regards,

Fran

![BlenderPluginError](https://user-images.githubusercontent.com/45069608/75634468-7591ac00-5c0e-11ea-9b89-05ff0db2cb84.jpg)

**Comment by Aranuvir** [comment]
The error message in your screen shot is quite verbose. And the last line is telling you what is going wrong. The plugin cannot connect to MakeHuman for whatever reason: connections not accepted inside MakeHuman, wrong ip, wrong port, M$ (in)security features blocking the connection...

Most likely nothing that can be fixed inside the plugin, therefore closing.
