### ISSUE TITLE
Error when trying to enable the MakeHuman Community Plugin in Blender 2.79

### ISSUE THREAD

**Issue by EDX442** [makehumancommunity/makehuman-plugin-for-blender#66]
I get this error message:

![Untitled](https://user-images.githubusercontent.com/46428678/76868477-eb2c8780-685e-11ea-9505-31ef2b8bc7a5.png)

Can anyone help?

I've also tried installing the MHX2 plugins I've found but they don't even seem to install as they don't appear in the plugin list.

**Comment by Aranuvir** [comment]
>Can anyone help?

Yes, update to Blender 2.82a...
