### ISSUE TITLE
Kinect 360 with USB connection not working

### ISSUE THREAD

**Issue by smithian123** [makehumancommunity/makehuman-plugin-for-blender#67]
The tooltip on the 'Type: Kinect2' drop list indicates that a kinect from an xbox360 will work. However upon hitting 'Record' I receive an error message about a missing dll;

Error DLL: KinectotoJSON_x64.dll, on path: C:\Users\Admin\Appdata\Roaming\Blender Foundation\Blender\2.82\addons\MH_Community\mocap\kinect2, failed to load. Is Kinectt re-distributable installed?

Can this be addressed to make an xbox360 (working correctly with other software on PC) functional or is it only for Kinect2 hardware?

Thanks,
Ian

**Comment by Palmer-JC** [comment]
No, the SDK between the Kinect2 is different & as well as the # of bones.
I have generalized the code to possibly handle the next Kinect, Kinect
Azure, but that is still a developer product.

I do not have Kinect360 nor a Kinect Azure, as well.
