### ISSUE TITLE
Blender 2.82 crashes with makehuman plugin 0.6.3 with Mesh -> "Import Human", ubuntu linux

### ISSUE THREAD

**Issue by nattydread69** [makehumancommunity/makehuman-plugin-for-blender#69]
As in the title I try to " import human" with makehuman plugin 0.6.3
on ubuntu linux 20.04

blender crashes with the following output on the command line:

/usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x72ffd) [0x7f4ffb769ffd]
BLI_assert failed: /build/blender-RL3axj/blender-2.82.a+dfsg/source/blender/bmesh/operators/bmo_normals.c:121, recalc_face_normals_find_index(), at 'BM_face_is_normal_valid(faces[i])'
Aborted (core dumped)
The output in makehuman is:

Starting server thread.
Opening server socket... 
Opened on host 127.0.0.1
Opened at port 12345

Waiting for connection.
Connected with 127.0.0.1:53634
Client says: '{
  "function": "getBodyMeshInfo",
  "error": "",
  "params": {

  },
  "data": null
}
'
About to serialize JSON. This might take some time.
Waiting for connection.
Connected with 127.0.0.1:53636
Client says: '{
  "function": "getBodyVerticesBinary",
  "error": "",
  "params": {

  },
  "data": null
}
'
Waiting for connection.
Connected with 127.0.0.1:53638
Client says: '{
  "function": "getBodyFacesBinary",
  "error": "",
  "params": {

  },
  "data": null
}
'
Waiting for connection.
Connected with 127.0.0.1:53640
Client says: '{
  "function": "getBodyTextureCoordsBinary",
  "error": "",
  "params": {

  },
  "data": null
}
'
Waiting for connection.
Connected with 127.0.0.1:53642
Client says: '{
  "function": "getBodyFaceUVMappingsBinary",
  "error": "",
  "params": {

  },
  "data": null
}
'
Waiting for connection.

I originally opened this bug report for blender  and this was the feedback:

Robert Guetzkow (rjg) claimed this task.
It looks like the add-on creates a mesh with invalid normals, which triggers the assert, similar to T75394. This doesn't seem to be a bug in Blender but improper mesh generation by the makehuman add-on. There's probably a bm.normal_update() missing.

Please report the issue to the developers of the add-on.

I'm closing this report, because the issue is most likely in the third-party add-on. Please follow the submission template for future bug reports. This guide may help to decide where the issue should be reported.

**Comment by robertguetzkow** [comment]
Please note that @nattydread69 was using a debug build, which is why the assert was triggered. See [T76657](https://developer.blender.org/T76657) on Blender's bug tracker.

**Comment by nattydread69** [comment]
Although I installed blender from the ubuntu repositories. I'm not sure why that wouldn't be the release version.

**Comment by joepal1976** [comment]
We recommend against using ubuntu's blender, based on prior experiences. 

But looking into a missing normal update seems like a sensible thing to do anyway.

**Comment by nattydread69** [comment]
I downloaded the release blender and I can confirm that it works correctly now.
