### ISSUE TITLE
Helper Geometry Delete on import does the inverse

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/makehuman-plugin-for-blender#71]
When you select Delete under 'How to handle Helpers', instead of deleting the helper geometry, it makes it the imported geometry. So, my female character looks like she is wearing a robe coveredin small cubes, and has a penis.

**Comment by joepal1976** [comment]
Ouch.

Confirmed, and on it.

**Comment by joepal1976** [comment]
I think this should fix it. You can download the latest version from github if you want it now.

Otherwise, the plugin will be automatically built and uploaded tomorrow morning, so if you wait some 20 hours from now you can then get it via the nightly build of makehuman or from the plugins page.

**Comment by Hunanbean** [comment]
Thank you very much for the quick response. While this did delete the
helper geometry, it now leaves the only vertex group after import as
"delete". This seems to disable "maketarget2" and "makeshape"
functionality, amongst other general issues caused by the missing vertex
groups. I sincerely appreciate all the work you all are doing, thank you
for making these things possible!
