### ISSUE TITLE
Adapt "Dump vgroups" so that it can be used on windows

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/makehuman-plugin-for-blender#73]
Error: Traceback (most recent call last):
  File "C:\Users\MyAccountName\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MH_Community\devtools\printvgroups.py", line 32, in execute
    with open("/tmp/vgroups.py", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/vgroups.py'

location: <unknown location>:-1

all software and plugins updated to latest with dates of 5/31/2020

**Comment by joepal1976** [comment]
This is a developer function intended for debugging, and it's currently written for linux only.

This said, there's no obvious reason why it couldn't be adapted to work on windows too.

**Comment by Hunanbean** [comment]
Understood, thank you for the clarification.

**Comment by Hunanbean** [comment]
It is currently working under windows.

Thank you
