### ISSUE TITLE
NoneType error when click "import human"

### ISSUE THREAD

**Issue by epth** [makehumancommunity/makehuman-plugin-for-blender#76]
makehuman version: makehuman-community-20200711-windows
makehuman blender plugin version: 0.6.3
blender version: 2.83.2
![image](https://user-images.githubusercontent.com/25238420/87223630-22e0b180-c3b1-11ea-840b-962d1f17c546.png)

**Comment by Aranuvir** [comment]
Could you give more information how to reproduce the issue? Specific settings in the plug-in? Specific assets, materials, etc.? And please make sure you got the latest versions of MakeSkin and mhapi.

**Comment by epth** [comment]
> 
> 
> Could you give more information how to reproduce the issue? Specific settings in the plug-in? Specific assets, materials, etc.? And please make sure you got the latest versions of MakeSkin and mhapi.

I just click the button bellow, the NakeHuman_community.exe is opening and is the default settings for character.
![image](https://user-images.githubusercontent.com/25238420/87238057-3bdc7780-c430-11ea-9b2f-dbd4a3999abc.png)


other settings are default,i dont know which MakeSkin and mhapi version I'm using. All files I downloaded from :
http://download.tuxfamily.org/makehuman/nightly/makehuman-community-20200711-nightly-windows.zip

Is this your official build and the newest version?

**Comment by Aranuvir** [comment]
Does this issue still occur?

**Comment by epth** [comment]
@Aranuvir 

No,it runs perfect with Blender2.90.1 and MH-Plugin nightly now,thank you a lot!
