### ISSUE TITLE
Additional geometry, i.e. teeth, have no vertex groups on import

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/makehuman-plugin-for-blender#88]
Any non main body model imported has no vertex groups.
I honestly am not sure if this is intended or an oversight

here is the forum post about it [http://www.makehumancommunity.org/forum/viewtopic.php?f=3&t=18771](url)

Thank you

**Comment by Aranuvir** [comment]
VGs are only on the helpers and on the meshes as long as they are needed for the armature.

**Comment by Hunanbean** [comment]
Understood. it was more of a request than an error report. I was hoping to perhaps discuss it in the forum link

Thanks for the info
