### ISSUE TITLE
Blender's Makehumans missing materials/ Uv shaders By Fakey-Person

### ISSUE THREAD

**Issue by Head-Hunter-is-OP** [makehumancommunity/makehuman-plugin-for-blender#89]
![bandicam 2020-11-30 16-38-03-051](https://user-images.githubusercontent.com/75588649/101400091-6545e600-389e-11eb-86c3-2d36b4630d6f.png)

I had many people in my scene in Blender, and some of them were all white, I then check there Uv and shaders... They didn't have any.
The white/no shader

![bandicam 2020-11-29 15-54-11-786](https://user-images.githubusercontent.com/75588649/101400023-49424480-389e-11eb-8dae-75d5c728d8a1.png)

another person with all the shaders and Uvs

![bandicam 2020-11-30 16-38-09-611](https://user-images.githubusercontent.com/75588649/101400143-742c9880-389e-11eb-88d9-809c785bb32e.png)

OK the other UV image is another make a human model with her denim jacket

OK we may have the same issue, but it was different causes, I have any other humans which are not textures or all white

ok THIS Is kinda annoying, this is basically saying is you can't you're Makehuman models as filler or have more than with the same skin. this is angering me, this may be a Bug, That happens ALl the time. NO MATTER if you put ON, it will lead to the same way. so IN YOUR SCENES, YOU CAN ONLY USE ONE OF THE SAME SKIN ONCE OR MORE
![bandicam 2020-12-05 05-35-54-063](https://user-images.githubusercontent.com/75588649/101400204-8eff0d00-389e-11eb-8306-247d3a36d662.png)
![bandicam 2020-12-05 05-36-15-576](https://user-images.githubusercontent.com/75588649/101400207-8eff0d00-389e-11eb-8b10-3aba0b74193c.png)
![bandicam 2020-12-05 05-36-37-427](https://user-images.githubusercontent.com/75588649/101400208-8f97a380-389e-11eb-9fa8-c692899be9c6.png)

and if it is just me, I feel attacked, My laptop is pretty decent, so I dare you

P.S this ruined 3 of my scenes because of this BUG.

I'm just reciting what @ https://github.com/Fakey-Person , sorry I don't know to Github, Nor have I ever used Github, I have been requested to do this by  https://github.com/Fakey-Person , this man is a sicko for me btw, he "said" he couldn't do this, I really don't know how he found my email, anyway this came from him

**Comment by Fakey-Person** [comment]
Hey the images are in the wrong places

**Comment by Head-Hunter-is-OP** [comment]
well soorrry get off of my D*ck Please

**Comment by Fakey-Person** [comment]
...........no..........

**Comment by Head-Hunter-is-OP** [comment]
OK Im kinda running into this problem to

**Comment by Head-Hunter-is-OP** [comment]
Thanks, Aranuvir

**Comment by Head-Hunter-is-OP** [comment]
OK I'm getting this no shader think as well, it is angering me a bit, why, what, and how is this caused, this is tedious. it could be fixed with make skin, but some of the presets in makehuman aren't in your files to import the skin from the file

**Comment by Head-Hunter-is-OP** [comment]
Ok, this white glitch is pretty annoying, here it seems only to work when I used the Young Asian female. and then it turns white if you use this skin
![bandicam 2020-12-08 17-50-47-892](https://user-images.githubusercontent.com/75588649/101555126-fb087080-3985-11eb-9ac5-e6ae00277cda.png) me pressing the woman with young Asian skin; girl next to with a different skin

**Comment by Head-Hunter-is-OP** [comment]
I'm sorry i missclicked

**Comment by Head-Hunter-is-OP** [comment]
can somebody unclose this, please... ugh

**Comment by Fakey-Person** [comment]
YOU....YOU closed it!!?!?!?!
