### ISSUE TITLE
The programmer recruiting forum message

### ISSUE THREAD

**Issue by Palmer-JC** [makehumancommunity/makehuman-plugin-for-blender#96]
I check the forum, though I cannot log onto it, so replying here where it might be seen.  On option might be to try chatGPT in some of the corners where you are lacking.  Not much to lose trying.

---
I am not that familiar with Python in an executable.  Even in Blender, I picked Python up at the same time.  I do have loose plans for some of the code in this repo that I still use which is:

- Code to make custom skeletons (ditching the motion capture for which it was for though).
- Code to drag across expressions as shapekeys.

I would probably do in in stages, so I did not have to do it all at once:
- Check if the newer plugin generates meshes, with which I can still run the functionality stated above.  If so, remove all that functionality overlap here along with motion capture.
- Make sure what is left still works.  I see problems coming to expressions to a pose library in current versions of Blender (planning to ditching that too unless it still works).
- Move any stuff to the new plugin, that is if you wish it.  In any case, probably not going the try to republish this repo.

**Comment by joepal1976** [comment]
Thanks for the feedback.

Concerning the recruitment message, that was mostly aimed at finding enough people for a targeted effort at updating the standalone GUI application. That said, there's plenty to be done on the blender side too.

As you have probably noticed, this repo no longer sees a lot of action. At the same time, several of the things that remain here but are unported would be valuable in the MPFB2 code base. I would much appreciate help with porting these things.

Let me know if if there is anything that could be of help when porting stuff. I know the documentation is, as usual, severely lacking. I'm sure there are areas which might seem rather arcane at a first glance.
